### ISSUE TITLE
My Servers Website

### ISSUE THREAD

**Issue by technomonster0** [ProjectInfinity/PocketVote#10]
Wanted to report that the My servers section of the PocketVote Website isn't working.

**Comment by ProjectInfinity** [comment]
Works great for me so I'm going to need more details than that.

**Comment by technomonster0** [comment]
pocketvote.io/servers Was not working for me.

**Comment by ProjectInfinity** [comment]
I need details. Like I said it's working for me and for others too. What's not working?

**Comment by PixelPlugins** [comment]
It doesn't work for me either. It just says "Whoops! Looks like something went wrong!" with a ghost icon in the corner that says "exceptional"

**Comment by HimbeersaftLP** [comment]
Hmm, seems to work fine for me though

**Comment by ProjectInfinity** [comment]
This has been resolved.
