### ISSUE TITLE
Warning console & Mysql (NULL) values

### ISSUE THREAD

**Issue by HoverEpic** [ProjectInfinity/PocketVote#11]
Hi, i've juste installed **PocketVote v2.0.2** on PocketMin-MP (1.7dev API 3.0.0-ALPHA7) and i have some warning in console :

```
Warning: Attempt to modify property 'player' of non-object in phar:///home/root/mcpe/plugins/PocketVote-PocketMine_2.0.2.phar/src/ProjectInfinity/PocketVote/task/VoteCheckTask.php on line 98

Warning: Attempt to modify property 'ip' of non-object in phar:///home/root/mcpe/plugins/PocketVote-PocketMine_2.0.2.phar/src/ProjectInfinity/PocketVote/task/VoteCheckTask.php on line 98

Warning: Attempt to modify property 'site' of non-object in phar:///home/root/mcpe/plugins/PocketVote-PocketMine_2.0.2.phar/src/ProjectInfinity/PocketVote/task/VoteCheckTask.php on line 98
```

I juste check my database and in "pocketvote_table", i have an weird row :

```
    id  player  ip      site     timestamp  
------  ------  ------  ------  ------------
     1  (NULL)  (NULL)  (NULL)    1505138922
```

I think i've configured all things good, Is it normal?

**Comment by ProjectInfinity** [comment]
That's really weird but I'll add some null checks. Can you confirm that other players appear correctly in the table?

**Comment by HoverEpic** [comment]
I'ts a local testing server, i'll try with other accounts in few minutes (and wish it's not vote IP based to complete the process).

edit : and it is, so i'll try tomorrow =P

**Comment by ProjectInfinity** [comment]
@HoverEpic saw your edit, do other players appear correctly?
