### ISSUE TITLE
[Server thread/ ERROR]

### ISSUE THREAD

**Issue by ghost** [ProjectInfinity/PocketVote#12]
Keep getting the serverthread/error for pocketvote saying "Votechecktask: Missing indentity"

What is it that i'm doing wrong?
Each identity is set for each server.

**Comment by ProjectInfinity** [comment]
What server software are you using and what version as well as your PocketVote version?

**Comment by ghost** [comment]
v1.2.0.81
PocketMine-MP 1.7dev-355.phar

PocketVote version 2.0.2


I was able to get the plugin to load (and the error went away) but now its as if no votes are being registered.  Really in need of a multi-server vote plugin that utilizes mysql.

Thanks for the quick response.
[PocketVote_v2.0.2-alpha9.phar.zip](https://github.com/ProjectInfinity/PocketVote/files/1468353/PocketVote_v2.0.2-alpha9.phar.zip)

**Comment by ProjectInfinity** [comment]
Can you post your config.yml file with your identity and secret removed?

**Comment by ghost** [comment]
I forgot to mention I'm also using a multi-server setup.

Hub
`dev: false
version: 4
identity: xxxxxxxxxxxxxxxxxxx
secret: xxxxxxxxxxxxxx
lock: false
vote-expiration: 14
multi-server:
    enabled: true
    role: master
    mysql: { host: play.xxxxxxx.in, port: xxxx, username: xxxxx, password: xxxxxx, database: pocketvote }
onvote:
    run-cmd: ['say %player has voted for us on %site.  Thanks!']
    online-cmd: {  }
votes: {  }
`


Factions
`dev: false
version: 4
identity: xxxxxxxxxxxxxxx
secret: xxxxxxxxxx
lock: false
vote-expiration: 14
multi-server:
    enabled: true
    role: slave
    mysql: { host: play.xxxxxx.in, port: xxxxx, username: xxxxx, password: xxxxxxxx, database: pocketvote }
onvote:
    run-cmd: ['say %player has voted!']
    online-cmd: ['give 1', 'give 2', 'give 3']
votes: {  }
`


[config.zip](https://github.com/ProjectInfinity/PocketVote/files/1468373/config.zip)

**Comment by ghost** [comment]
So, to make the error go away you have to  enter the secret and identity from in-game to each server.  But it still doesn't seem to make a difference aside from eliminating ""Votechecktask: Missing indentity" error.

Still unable to receive a vote :(
