### ISSUE TITLE
Votecheck Task error line 98

### ISSUE THREAD

**Issue by ghost** [ProjectInfinity/PocketVote#13]
https://i.gyazo.com/515edbd9185cd7245b1e6af3ac4e21d1.png

**Comment by ProjectInfinity** [comment]
I have figured where the issue happens. I just need some time to set up my multi-server environment as I have not done that in a while.

**Comment by ProjectInfinity** [comment]
This should fix it.

https://poggit.pmmp.io/r/16171/PocketVote-PocketMine_dev-20.phar
