### ISSUE TITLE
Unable to view more then 3 gu.

### ISSUE THREAD

**Issue by ghost** [ProjectInfinity/PocketVote#14]
When you use the command  guadd to add your vote sites,   if you have more than 3 sites added to your list you are unable to view with gulist. 

Clarification,    If you you have 4 in the list, you can only view the first 3 but not the fourth.
If the case is you have more than 3 then you can not view the ID for the 4th to delete or edit,  so you have to delete number 3 to make number 4->3 to see the id.   

Not necessarily a game changing bug,  just a bit of an annoyance.

**Comment by ProjectInfinity** [comment]
Can you post your vote link and is it still doing this?
