### ISSUE TITLE
New Supported voting site

### ISSUE THREAD

**Issue by byluz** [ProjectInfinity/PocketVote#16]
Hello, we have been talking on gitter. You said to open an issue :). My site is MinecraftPE-Servers.com 

Regards,
Austin

**Comment by ProjectInfinity** [comment]
Your site has been added to the list. Could you please provide some screenshots that show your pocketvote implementation?

**Comment by byluz** [comment]
Just sent you the message!

**Comment by ProjectInfinity** [comment]
Added.
