### ISSUE TITLE
pocketvote plugin wont work?

### ISSUE THREAD

**Issue by MKBandzz** [ProjectInfinity/PocketVote#2]
when im trying to get this plugin to work, it wont. There is no identity/identifier, and it isnt detecting the secret key even when i enter it in via console.
![p4](https://cloud.githubusercontent.com/assets/19160618/15260888/4c376d46-1927-11e6-8294-7fd1c759e75f.PNG)
![p1](https://cloud.githubusercontent.com/assets/19160618/15260890/4c3cec9e-1927-11e6-8fcb-009552928e89.PNG)
![p2](https://cloud.githubusercontent.com/assets/19160618/15260891/4c3e4e54-1927-11e6-866d-62ad6b0c5aaf.PNG)
![p3](https://cloud.githubusercontent.com/assets/19160618/15260889/4c3ca18a-1927-11e6-93b7-b28c623ca7ee.PNG)

**Comment by ProjectInfinity** [comment]
Very odd. Is this version 1.1.3?

**Comment by ProjectInfinity** [comment]
Issue resolved. It was a case of a missing extension on the newly migrated machine. Unfortunately I will need you to recreate your server, but rest assured this won't happen again.

**Comment by MKBandzz** [comment]
Ok. Will I need to do anything like download another phar? or do i just need to recreate?

**Comment by ProjectInfinity** [comment]
Just recreate the server on the site.
