### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by Matthww** [ProjectInfinity/PocketVote#20]
Pocketvote has stoppped receiving votes since February 17th.

**Comment by ProjectInfinity** [comment]
On which voting site?

**Comment by Matthww** [comment]
minecraftpocket-servers.com

**Comment by ProjectInfinity** [comment]
Are other sites working for you?

**Comment by Matthww** [comment]
@ProjectInfinity No idea I only use that website

**Comment by ProjectInfinity** [comment]
Have you tried using /pv diagnose? What does it say?

**Comment by Matthww** [comment]
```
[05:02:13] [Server thread/INFO]: Scheduling a diagnosis...
[05:02:14] [Server thread/INFO]: ▒ Found server
[05:02:14] [Server thread/INFO]: ▒ Has votes (trivial)
[05:02:14] [Server thread/INFO]: ▒ Decode sample vote
[05:02:14] [Server thread/INFO]: A test vote will be dispatched momentarily. If more than a couple of minutes passes the dispatch has failed.
````

Votes: 
```
votes:
- player: PocketVoteSample
  site: pocketvote.io
  ip: 127.0.0.1
  expires: 1520334136
```

**Comment by ProjectInfinity** [comment]
Seems like your config is correct. Does this site always fail or does it work sometimes? I've heard reports about other sites not working but there seems to be no consistency in what works or doesn't work.

**Comment by Matthww** [comment]
It always worked but it stopped working on February 17th (10 days ago)

**Comment by diffen** [comment]
@Matthww Try it on MinecraftList.org and I'll help debug.

**Comment by ProjectInfinity** [comment]
I have sent an email to the guy behind minecraftpocket-servers.com. I am curious to see if this is an issue on my or his end.

Also try what @diffen suggested. It would be nice to ensure the issue is not on my end.

**Comment by ProjectInfinity** [comment]
I have confirmed an issue with the site in question. I have sent the owner a new email with details. Hopefully we can get this sorted asap.
