### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by XDqrkneZ** [ProjectInfinity/PocketVote#21]
i read the instructions and registed my server on https://minecraftpocket-servers.com/ and there was no where to put the secret that pocketvote provided. also, is there /vote command in game to confirm the vote? for identifier, do i put that in `identity: ''`? for `secret: ''`,  do i put the secret that the web gave me? The `Copy and paste this secret into server lists:`

**Comment by ProjectInfinity** [comment]
It's probably under "LEET". PocketVote is misrepresented as a service for LEET users on minecraftpocket-servers.com, PocketVote works for everybody.

When you click `show secrets` on https://pocketvote.io/servers, copy the identity and secret and put them into your config.yml file.

And do the same for the voting site, they'll probably ask for your identity.

**Comment by XDqrkneZ** [comment]
when will these run?
`onvote:
  run-cmd:`
  - `'say Thanks for voting for us at %site, %player!'`
  online-cmd:
  - `'tell %player Thank you for voting for us.'`

**Comment by ProjectInfinity** [comment]
As the name says.

`run-cmd` will run on receiving a vote (instantly, you do not type /vote with PocketVote).
`online-cmd` will run whenever the player is online (instant if they are already online, otherwise it will wait until they log in).

**Comment by XDqrkneZ** [comment]
nice. I got it thanks
