### ISSUE TITLE
Issue with link

### ISSUE THREAD

**Issue by xrcher** [ProjectInfinity/PocketVote#26]
Hi, whenever someone types /vote and goes to the guru link, it just forwards them to the pocketvote homepage. Please Help

**Comment by ProjectInfinity** [comment]
What's your link?

**Comment by nebsonc** [comment]
Hello, I setup the link and all, whenI voted I did not appear on top 10 voters.

**Comment by ProjectInfinity** [comment]
Give it 24 hours and again. The leader boards don't update instantly.

**Comment by ProjectInfinity** [comment]
@DeveloperNeb101 Please open your own issue on Github and explain what steps you've done and what your server ip is so I can look it up in our system.
