### ISSUE TITLE
new server list

### ISSUE THREAD

**Issue by MaDie** [ProjectInfinity/PocketVote#28]
hi, i integrated your api in my new bedrock server list and would be pleases when you add my server list to your references: https://bedrock.minecraft-server.eu/

**Comment by ProjectInfinity** [comment]
Hi, is this site only in German?

**Comment by MaDie** [comment]
no, it is also available in english: https://bedrock.minecraft-server.eu?lang=en

**Comment by ProjectInfinity** [comment]
How do users enter their username while voting? From what I could see that
wasn't possible, instead I could only click vote.

**Comment by MaDie** [comment]
the pocket vote implementation has to be set up for the server. that means the server operator has to enter the secret, otherwhise there is no input field for the name.

i just configured my test server, so you can test it here: https://bedrock.minecraft-server.eu/vote/index/20140?lang=en

this server is listed at pocketvote.io with id 759500

**Comment by ProjectInfinity** [comment]
I have posted a vote and will inspect the data I received when I have time. Is there any plans to provide an English category on your forums? I do not mind promoting websites that are not strictly English but I would have to mark your site as German speaking to avoid confusing end users.

**Comment by MaDie** [comment]
no, there are not any plans to provide a english speaking forum. 7 years ago we started as a german speaking minecraft java community and today we are the biggest one. tomorrow we will announce the bedrock/pocket serverlist and our plan is, like we did it with our minecraft classic community, to target only german speaking players and servers, cause there are enough english speaking communities.

**Comment by ProjectInfinity** [comment]
The data seems fine. 

The website will be added with some sort of warning that it is intended for German speaking players during the next site update.

**Comment by ProjectInfinity** [comment]
Also, you can join my discord which I will be starting to use to better communicate with server list operators.

https://discord.gg/B4WHSSq

If you decide to join feel free to DM me so I can give you access to the channel I will be using.
The goal is to better communicate changes and allow discussion regarding API changes or future features.

**Comment by ProjectInfinity** [comment]
Site is now featured.
https://pocketvote.io/#sites
