### ISSUE TITLE
I want my server in the list. 

### ISSUE THREAD

**Issue by ZenSirzechs** [ProjectInfinity/PocketVote#29]
Is this where I ask for my server to be listed? How do I do it?

**Comment by ProjectInfinity** [comment]
No, you do not ask for your server to be listed. You simply login to pocketvote.io and add it yourself.

**Comment by ZenSirzechs** [comment]
"If you own a server listing that supports PocketVote, open a Github Issue and we’ll get you added to the list."?

**Comment by ProjectInfinity** [comment]
That's for server listings. Meaning websites that list servers that you can vote for, aka voting sites.

**Comment by LDKLucifer** [comment]
Yeah, don't I need my server to be listed there so people can vote?

I'll ask something else. I'm registered in poketvote.io but how will people vote for the server and plugin will receive it?
