### ISSUE TITLE
Freezes server startup on Genisys

### ISSUE THREAD

**Issue by DegenApeDev** [ProjectInfinity/PocketVote#3]
I added the plugin and updated the config with the secret and key when I start the server on Genisys it just hangs on this. 

[12:56:40] [Server thread/INFO]: Enabling PeacefulSpawn v2.4
[12:56:40] [Server thread/INFO]: Enabling PocketVote v1.1.3

Won't go any further I waited for 5 minutes..

**Comment by ProjectInfinity** [comment]
Do you have cURL disabled in your PHP binaries' .ini file? On first load it will download a file called cacert.pem from the official cURL website. Does this file exist locally for you in the PocketVote plugin folder?

The file in question is: https://curl.haxx.se/ca/cacert.pem
Feel free to download it manually. It's done the first time sync so the plugin does not go ahead and fully load when the certificate file is not present as to avoid any unverified calls to the PocketVote servers.

**Comment by DegenApeDev** [comment]
Well perhaps thats the problem I can't seem to download that cacert.pem it time outs network error..

**Comment by ProjectInfinity** [comment]
Very weird. Could you try downloading the file manually and placing it within the PocketVote plugin folder, then restarting your server?

**Comment by DegenApeDev** [comment]
Yeah thats what I mean, I can't even download it manually..  The site is not responding.. Any other mirror I can get that file??

**Comment by ProjectInfinity** [comment]
No. If that site is not responding then it's likely it's being blocked on your end. Are you running any weird software on your computer and or router that is supposed to "protect" you? That is the official cURL website and is totally trusted.

**Comment by DegenApeDev** [comment]
Well, it's not just my computer it's also the server that cannot access it.. Have you tried to the link?? The whole domain seems to be down.

**Comment by ProjectInfinity** [comment]
I have been using it without issues for years. But I'll mirror the file for now if this starts becoming an regular occurrence. Give me a minute.

**Comment by ProjectInfinity** [comment]
https://s3.eu-central-1.amazonaws.com/pocketvote/cacert.pem

File can be downloaded there.
