### ISSUE TITLE
Cant start up PocketVote

### ISSUE THREAD

**Issue by marvinchen130** [ProjectInfinity/PocketVote#30]
I downloaded the plugin from poggit.pmmp.io and once i put in my key and identity, i keep getting this error: [14:57:27] [Server thread/CRITICAL]: ErrorException: "yaml_parse(): parsing error encountered during parsing: did not find expected ',' or ']' (line 17, column 17), context while parsing a flow sequence (line 17, column 12)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 181

**Comment by ProjectInfinity** [comment]
Your YAML file is corrupt. It contains invalid characters.

Read the error and find the line in question, either reset your config or fix it from the error message.
