### ISSUE TITLE
I cant add server

### ISSUE THREAD

**Issue by Nch002** [ProjectInfinity/PocketVote#31]
I type in FmFactions as name 127.0.0.1 as ip and 19132 as adress and hit add it doesnt show my server

**Comment by ProjectInfinity** [comment]
127.0.0.1 is not a valid server IP.

You need to set your external IP as your server IP.
If you are hosting the server locally go here and enter the IP shown here:
[WhatIsMyIP.com](https://www.whatismyip.com/)

**Comment by Nch002** [comment]
it is pocketmine-mp

**Comment by ProjectInfinity** [comment]
That is not an IP.

**Comment by Nch002** [comment]
so how do i find it out under pocketmine-mp

**Comment by ProjectInfinity** [comment]
https://www.whatismyip.com/

**Comment by Nch002** [comment]
no im using the app pocketmine-mp

**Comment by ProjectInfinity** [comment]
Then you cannot use PocketVote. PocketVote requires internet access and the android app for PocketMine does not have that. You need to host your server on a computer.

**Comment by Nch002** [comment]
i fixed it i used ip changer
