### ISSUE TITLE
Login is broken

### ISSUE THREAD

**Issue by Wertzui123** [ProjectInfinity/PocketVote#37]
I created a new account, because I couldn't login to my old account. I logged out, and when I tryed to log in:

Error
Invalid credentials. Please check your email and password.

I'm login in with the exact same passwort and email, with wich I created the account. Why is this happening?

**Comment by Wertzui123** [comment]
I already had this problem in #34

**Comment by ProjectInfinity** [comment]
Ensure you're actually logging in with the right credentials.

To make sure that it actually works I changed my password using the site and it worked just fine. You must be doing something wrong. Use Chrome and start a incognito session so no extensions or anything are messing with your session.

**Comment by Wertzui123** [comment]
I'll try this.

**Comment by Wertzui123** [comment]
Doesn't work

**Comment by ProjectInfinity** [comment]
Contact me on discord. It works for me

**Comment by Wertzui123** [comment]
Ok
