### ISSUE TITLE
How do players vote?

### ISSUE THREAD

**Issue by Bidou0418** [ProjectInfinity/PocketVote#4]
I have installed everything but how exactly do my players vote for my server?
Is there a command?
I dont even see anything as loaded in my web console..
https://pocketvote.io/#services; says it supports pocketmine 1.2???1.6
Genisys dev416

is this another Nukkit plugin only?

**Comment by ProjectInfinity** [comment]
They need to go to the websites where they would have to vote anyhow.
Something like Minecraftlist.org

**Comment by Bidou0418** [comment]
oh, i thought and would it not be cooler if all they had to do was to click on a vote sign...
having to go to a web site, search the server and then vote is rather time consuming..

**Comment by ProjectInfinity** [comment]
That's not possible.
