### ISSUE TITLE
Gulist crashing server

### ISSUE THREAD

**Issue by CtrlAltTr0ll** [ProjectInfinity/PocketVote#41]
PocketMine-MP Crash Dump Thu Sep 5 14:33:42 UTC 2019

Error: Invalid argument supplied for foreach()
File: plugins/PocketVote-PocketMine.phar/src/ProjectInfinity/PocketVote/task/guru/GetLinksTask
Line: 61
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PocketVote v3.0.1

**Full crash report link:**
[Safari - Sep 5, 2019 at 11:01 AM.pdf](https://github.com/ProjectInfinity/PocketVote/files/3579890/Safari.-.Sep.5.2019.at.11.01.AM.pdf)

**Comment by ProjectInfinity** [comment]
What is the IP and port that you added on your server? That way I can attempt to figure out what happened here. Something seems to be incorrect with the data for your server, so I need to be able to identify.

**Comment by CtrlAltTr0ll** [comment]
I figured it out, I feel stupid lol

In the config file where it says

secret: “”
Identity: “”

I added the codes between the “” instead of replacing them with the codes.

I reinstalled the plugin and used the in-game GUI and it works now.
