### ISSUE TITLE
Votes not working

### ISSUE THREAD

**Issue by CrazySniper52** [ProjectInfinity/PocketVote#44]
The votes for my server on minecraftpocket-servers.com isnt going through to my games vote rewards. Ive put the secret and the id in the correct places on both the vote website and in my plugin-date, so im confused to why its not working.

**Comment by mrpwes** [comment]
![image](https://user-images.githubusercontent.com/31194909/77642467-ac9e7780-6f98-11ea-9850-10b94f21d7ba.png)
