### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by DegenApeDev** [ProjectInfinity/PocketVote#5]
Could we please have a feature that would allow server owners to specify a TIME in which the VOTES would expire so that when someone connects after DAYS of not being online they will NOT be flooded with rewards. 

I reckon a VALUE of DAYS should suffice for this as then we could expire the votes after 1,7,14 days

**Comment by MKBandzz** [comment]
It should be an option as alot of people wouldnt want this on their servers.
