### ISSUE TITLE
Unknown SSL protocol error

### ISSUE THREAD

**Issue by jasonw4331** [ProjectInfinity/PocketVote#6]
I receive this error on my PocketMine server every so often.

```
Unknown SSL protocol error in connection to api.pocketvote.io:443
35
```

**Comment by ProjectInfinity** [comment]
Could be your server is trying to connect using SSLv2 which I do not support. What are you running the server on?

**Comment by ProjectInfinity** [comment]
Please try this.

http://ci.regularbox.com/job/PocketVote-PocketMine/3/

**Comment by jasonw4331** [comment]
the server is run on ClearSky, the newest version, and I had to downgrade the plugin to php5 to be of use

**Comment by ProjectInfinity** [comment]
If it only happens on clearsky then it's up to them to fix it. I only
support PocketMine, none of the forks. Take it up with the fork if it
doesn't work.

**Comment by MKBandzz** [comment]
Genisys works great exept this popup comes if you reload your server thats the only downside:

`Notice: Undefined property: ProjectInfinity\PocketVote\PocketVote::$identity in phar://O:/Users/Mhikei2/Desktop/PocketMine-MP/plugins/PocketVote.phar/src/ProjectInfinity/PocketVote/task/SchedulerTask.php on line 20

Notice: Undefined property: ProjectInfinity\PocketVote\PocketVote::$secret in phar://O:/Users/Mhikei2/Desktop/PocketMine-MP/plugins/PocketVote.phar/src/ProjectInfinity/PocketVote/task/SchedulerTask.php on line 20
`

**Comment by ProjectInfinity** [comment]
@MhikeiMPC Sorry for the late reply. Currently I do not suggest reloading the plugin while the server is running. But I will take note and see if there's an elegant way to support that.
