### ISSUE TITLE
Nukkit plugin getting error 500 response codes

### ISSUE THREAD

**Issue by DaMatrix** [ProjectInfinity/PocketVote#8]
Votes aren't registered, instead there's an error in console and the vote checker thread dies.

**Comment by ProjectInfinity** [comment]
Please post logs, which site the vote is coming from and whatever else information that can help me identify the issue.

**Comment by DaMatrix** [comment]
The error is from pocketvote.io. It's printed on System.out and therefore not saved in the log, but here's a screenshot: http://imgur.com/G3QBg46

**Comment by ProjectInfinity** [comment]
Hmm, thanks. Does this happen often?

There was a slight downtime due to some upstream maintenance, it could be related to that. Let me know if it happens more.

**Comment by DaMatrix** [comment]
It's been being printed in the log ever minute-ish for the last 16 hours-ish. (sorry, don't know the exact time)

**Comment by ProjectInfinity** [comment]
Have you tried restarting the server?

**Comment by DaMatrix** [comment]
The server autorestarts once an hour.

**Comment by ProjectInfinity** [comment]
Thanks. I see there is an issue with the API contacting the database server. It's likely related to the maintenance upstream, but let me confirm this.

**Comment by DaMatrix** [comment]
OK, thanks :D

**Comment by ProjectInfinity** [comment]
Everything seems to be alright now. If your server is still not able to contact the API, which Java version are you on and what is your IP? I can attempt to contact your IP from the API servers to see if there's a routing issue on the way.

**Comment by DaMatrix** [comment]
It seems to work now, thanks :D
