### ISSUE TITLE
Some pages are inaccessible? 

### ISSUE THREAD

**Issue by theworstdrug** [ProjectInfinity/PocketVote#9]

**Comment by ProjectInfinity** [comment]
Please describe the issue.

**Comment by theworstdrug** [comment]
So I'm trying to set up my Voting system, and I can access the homepage just fine, but some things like pocketvote.io/dashboard/servers won't work. I managed to get around the server reg somehow but overall it's not working.

**Comment by ProjectInfinity** [comment]
Aha I changed this recently. Where are you linked to dashboard/servers? The url should point to /servers

**Comment by theworstdrug** [comment]
the documentation.

**Comment by theworstdrug** [comment]
It seems /servers doesnt work either.

**Comment by ProjectInfinity** [comment]
@Little2Epic https://pocketvote.io/servers works fine for me... is this the url you tried?

**Comment by theworstdrug** [comment]
![image](https://user-images.githubusercontent.com/16453706/28931010-4eb653f2-783a-11e7-894f-198b081abf4d.png)
mhm

**Comment by ProjectInfinity** [comment]
I've figured out the problem. Working on resolving it now.

**Comment by theworstdrug** [comment]
ECT? Not rushing you, just need to finish other stuffs.

**Comment by ProjectInfinity** [comment]
Should be working now. Please let me know.

**Comment by theworstdrug** [comment]
Yeah i just checked. Thanks so much for your help.
